config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html


  
  get 'posts/home' => 'posts#home'
  get 'posts/select' => 'posts#select'
  get 'posts/name' => 'posts#name'
  get 'posts/sect' => 'posts#sect'
  get 'posts/address' => 'posts#address'
  get 'posts/genre' => 'posts#genre'
  get 'posts/about' => 'posts#about'
  get 'posts/image' => 'posts#image'
  get 'posts/hokkaido'  => 'posts#hokkaido'
  get 'posts/touhoku'  => 'posts#touhoku'
  get 'posts/kanto'  => 'posts#kanto'
  get 'posts/tyubu'  => 'posts#tyubu'
  get 'posts/kinki'  => 'posts#kinki'
  get 'posts/tyubu'  => 'posts#tyubu'
  get 'posts/chusioku' => 'posts#chusioku'
  get 'posts/kyusyu'  => 'posts#kyusyu'
  
  resources :users, only: [:show]
  resources :posts do
    resources :likes, only: [:create, :destroy]
  end
  
 
  root 'posts#home'



  



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :user
  validates_uniqueness_of :post_id, scope: :user_id
  
end

app/models/post.rb
class Post < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :liked_users, through: :likes, source: :user 
 

      

      has_many :post_tag_relations, dependent: :destroy

      has_many :tags, through: :post_tag_relations, dependent: :destroy

end

app/models/post_tag_relation.rb
class PostTagRelation < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/tag.rb
class Tag < ApplicationRecord

    validates :name, presence: true
    
    has_many :post_tag_relations, dependent: :destroy
    
    has_many :posts, through: :post_tag_relations, dependent: :destroy 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
          devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable
          has_many :posts, dependent: :destroy
          has_many :likes, dependent: :destroy
          has_many :liked_posts, through: :likes, source: :post
          validates :name, presence: true 
          validates :profile, length: { maximum: 200 }
          def already_liked?(post)
            self.likes.exists?(post_id: post.id)
       
          end  
     mount_uploader :image, ImageUploader
        end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
  
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
   
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :profile, :image])

  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        like = current_user.likes.create(post_id: params[:post_id]) 
        redirect_back(fallback_location: root_path)
      end
    
      def destroy
        like = Like.find_by(post_id: params[:post_id], user_id: current_user.id)
        like.destroy
        redirect_back(fallback_location: root_path)
      end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user! 

  def home
      
  end

  def index
    @tag = Tag.select("name", "id")
      tag_search = params[:tag_search]
    if tag_search != nil
      @posts = Tag.find_by(id: tag_search).posts
    else
      @posts = Post.all
  end


    
 
    if params[:tag]
      Tag.create(name: params[:tag])
    end
    
    if params[:tag_ids]
      @posts = []
      params[:tag_ids].each do |key, value|
        if value == "1"
          tag_posts = Tag.find_by(name: key).posts
          @posts = @posts.empty? ? tag_posts : @posts & tag_posts
        end
      end
    end
  end

      def new
        @post= Post.new
      end
  
      def create
        post = Post.new(post_params)
        
        post.user_id = current_user.id

        if post.save
          redirect_to :action => "index"
        else
          redirect_to :action => "new"
        end
      end

      def show
        @post = Post.find(params[:id])
      end

      def edit
        @post = Post.find(params[:id])
      end 
    
      def update
        post = Post.find(params[:id])
        if post.update(post_params)
          redirect_to :action => "show", :id => post.id
        else
          redirect_to :action => "new"
        end
      end

      def destroy
        post = Post.find(params[:id])
        post.destroy
        redirect_to action: :index
      end

      def select

      end



      def hokkaido
        @hokkaido = Post.where(genre:"北海道") 
        @tag = Tag.select("name", "id")
        tag_search = params[:tag_search]
        if tag_search != nil
          @posts = Tag.find_by(id: tag_search).posts
        else
          @posts = Post.all
        end
      end
    
      def touhoku
        @touhoku = Post.where(genre:"東北") 
        @tag = Tag.select("name", "id")
        tag_search = params[:tag_search]
        if tag_search != nil
          @posts = Tag.find_by(id: tag_search).posts
        else
          @posts = Post.all
        end
      end
    
      def kanto
        @kanto = Post.where(genre:"関東") 
        @tag = Tag.select("name", "id")
        tag_search = params[:tag_search]
        if tag_search != nil
          @posts = Tag.find_by(id: tag_search).posts
        else
          @posts = Post.all
        end
      end
    
      def tyubu
        @tyubu = Post.where(genre:"中部")
        @tag = Tag.select("name", "id")
        tag_search = params[:tag_search]
        if tag_search != nil
          @posts = Tag.find_by(id: tag_search).posts
        else
          @posts = Post.all
        end 
      end

      def kinki
        @kinki = Post.where(genre:"近畿") 
        @tag = Tag.select("name", "id")
        tag_search = params[:tag_search]
        if tag_search != nil
          @posts = Tag.find_by(id: tag_search).posts
        else
          @posts = Post.all
        end
      end

      def chusioku
        @chusikoku = Post.where(genre:"中国・四国") 
        @tag = Tag.select("name", "id")
        tag_search = params[:tag_search]
        if tag_search != nil
          @posts = Tag.find_by(id: tag_search).posts
        else
          @posts = Post.all
        end
      end

      def kyusyu
        @kyusyu = Post.where(genre:"九州") 
        @tag = Tag.select("name", "id")
        tag_search = params[:tag_search]
        if tag_search != nil
          @posts = Tag.find_by(id: tag_search).posts
        else
          @posts = Post.all
        end
      end

      private

      def post_params
        params.require(:post).permit(:name, :sect, :address, :genre, :area, :about, :image, :lat, :lng, tag_ids: [])
      end

    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def show
        @user = User.find(params[:id]) 
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tera</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Slackside+One&display=swap" rel="stylesheet">

    <%= image_tag'aabbcc.png',class:'icon'%>
      <h1>ぼらんてら</h1>
      <div class="header-list">
      <ul>
        <li><%= link_to "ログイン", posts_path %></li>
        <li><%= link_to "新規登録", new_user_registration_path %></li>
        <li><%= button_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
        <li><%= link_to "新規投稿へ", new_post_path %></li>
        <li><%= link_to "検索へ",  posts_select_path %></li>
      </ul>
      </div>
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/posts/chusikoku.html.erb
<%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
    <%= text_field_tag :tag %>
    <%= submit_tag 'タグを追加' %>
  <% end %>

  <% @chusikoku.each do |t| %>
    <div class="Post">
      <%= t.user.email %> 
      <%= t.name %>
      
          <% if user_signed_in? %>
            <% if current_user.already_liked?(t) %>
              <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
                <p>いいねを取り消す</p><%= t.likes.count %>
              <% end %>
            <% else %>
              <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
                <p>いいね</p><%= t.likes.count %>
              <% end %>
            <% end %>
        <% else %>
          <p>いいねの数 = </p><%= t.likes.count %>
      <% end %>

      <%= image_tag t.image_url, size: "250x200" if t.image? %>

      <%= t.created_at %>
      <%= link_to "詳細へ", post_path(t.id) %>
      <% if user_signed_in? && current_user.id == t.user_id %>
        <%= link_to "編集する", edit_post_path(t.id) %>
        <%= link_to "削除する", post_path(t.id), method: :delete %>
      <% end %> 
      
    </div>
  <% end %>
</div>

app/views/posts/hokkaido.html.erb
<%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
  <%= text_field_tag :tag %>
  <%= submit_tag 'タグを追加' %>
<% end %>

<% @hokkaido.each do |t| %>
  <div class="Post">
    <%= t.user.email %> 
    <%= t.name %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <p>いいねを取り消す</p><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
              <p>いいね</p><%= t.likes.count %>
            <% end %>
          <% end %>
      <% else %>
        <p>いいねの数 = </p><%= t.likes.count %>
    <% end %>

    <%= image_tag t.image_url, size: "250x200" if t.image? %>

    <%= t.created_at %>
    <%= link_to "詳細へ", post_path(t.id) %>
    <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_post_path(t.id) %>
      <%= link_to "削除する", post_path(t.id), method: :delete %>
    <% end %> 
    
  </div>
<% end %>
</div>

app/views/posts/home.html.erb
<section id="first-block">

    <div class="top-block">
        ぼらんてら
    </div>
</section>

app/views/posts/index.html.erb
<div class="posts-container">
<%= link_to "トップページへ", posts_home_path %>
  <% if user_signed_in? %>
    <%= link_to "マイページへ", user_path(current_user.id) %>
  <% end %>

    <%= submit_tag '検索' %>

  
  

app/views/posts/kanto.html.erb
<%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
  <%= text_field_tag :tag %>
  <%= submit_tag 'タグを追加' %>
<% end %>

<% @kanto.each do |t| %>
  <div class="Post">
    <%= t.user.email %> 
    <%= t.name %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <p>いいねを取り消す</p><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
              <p>いいね</p><%= t.likes.count %>
            <% end %>
          <% end %>
      <% else %>
        <p>いいねの数 = </p><%= t.likes.count %>
    <% end %>

    <%= image_tag t.image_url, size: "250x200" if t.image? %>

    <%= t.created_at %>
    <%= link_to "詳細へ", post_path(t.id) %>
    <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_post_path(t.id) %>
      <%= link_to "削除する", post_path(t.id), method: :delete %>
    <% end %> 
    
  </div>
<% end %>
</div>

app/views/posts/kinki.html.erb
<%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
  <%= text_field_tag :tag %>
  <%= submit_tag 'タグを追加' %>
<% end %>

<% @kinki.each do |t| %>
  <div class="Post">
    <%= t.user.email %> 
    <%= t.name %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <p>いいねを取り消す</p><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
              <p>いいね</p><%= t.likes.count %>
            <% end %>
          <% end %>
      <% else %>
        <p>いいねの数 = </p><%= t.likes.count %>
    <% end %>

    <%= image_tag t.image_url, size: "250x200" if t.image? %>

    <%= t.created_at %>
    <%= link_to "詳細へ", post_path(t.id) %>
    <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_post_path(t.id) %>
      <%= link_to "削除する", post_path(t.id), method: :delete %>
    <% end %> 
    
  </div>
<% end %>
</div>

app/views/posts/kyusyu.html.erb
<%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
  <%= text_field_tag :tag %>
  <%= submit_tag 'タグを追加' %>
<% end %>

<% @kyusyu.each do |t| %>
  <div class="Post">
    <%= t.user.email %> 
    <%= t.name %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <p>いいねを取り消す</p><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
              <p>いいね</p><%= t.likes.count %>
            <% end %>
          <% end %>
      <% else %>
        <p>いいねの数 = </p><%= t.likes.count %>
    <% end %>

    <%= image_tag t.image_url, size: "250x200" if t.image? %>

    <%= t.created_at %>
    <%= link_to "詳細へ", post_path(t.id) %>
    <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_post_path(t.id) %>
      <%= link_to "削除する", post_path(t.id), method: :delete %>
    <% end %> 
    
  </div>
<% end %>
</div>

app/views/posts/new.html.erb
<h1>(自分の題名)</h1>
<h3>新規投稿ページ</h3>

<%= form_for @post do |t| %>

    <div class="field">
      <%= t.label :名前  %>
      <%= t.text_area :name, :size => "30x2" %>
    </div>

    <div class="field">
      <%= t.label :住所  %>
      <%= t.text_area :address, :size => "30x2" %>
    </div>

    <div class="field">
      <%= t.label :内容  %>
      <%= t.text_area :genre, :size => "30x2" %>
      <%= t.label :説明  %>
      <%= t.text_area :about, :size => "30x2" %>
    </div>

    <div class="field">
      <%= t.label :写真 %>
      <%= t.file_field :image %>
    </div>

    <div class='form-group'>
      <%= t.label :宗派 %>
        <%= t.collection_check_boxes(:tag_ids, Tag.all, :id, :name) do |tag| %>
          <li><%= tag.label { tag.check_box + tag.text } %></li>
        <% end %>
      </div>

    <div class='form-check'>
      <%= tag.label class: 'form-check-label' do %>
          <%= tag.check_box class: 'form-check-input' %>
          <%= tag.text %>
      <% end %>
    </div>

    <div class='area'>
      <%= t.label :地方を選択 %>
      <%= t.select :genre, ['北海道', '東北', '関東', '中部', '近畿', '中国・四国', '九州'] %>
    </div>

 <%= t.submit "投稿する" %>


<%= link_to "一覧に戻る", posts_path %>


<%= form_with(model: @post, local: true) do |f| %>
  <div class="actions">
    <%= f.label :address,"住所" %>
    <%= f.text_field :address %>
    <%= f.label :lat,"緯度" %>
    <%= f.text_field :lat,:value =>"緯度", id: :lat %>
    <%= f.label :lng,"経度" %>
    <%= f.text_field :lng,:value =>"経度", id: :lng %>
  </div>
<% end %>

<h2>Map</h2>

<input id="address" type="textbox" value="GeekSalon">
<input type="button" value="検索" onclick="codeAddress()">
<p>マーカーをドラック＆ドロップで位置の調整ができます。<p>
<div id='map'></div>

<style>
#map {
  height: 600px;
  width: 600px;
}
</style>

<script>
//初期マップの設定
let map
let marker
function initMap(){
  geocoder = new google.maps.Geocoder()

  map = new google.maps.Map(document.getElementById('map'), {
    center:  {lat: 35.6803997, lng:139.7690174},  //東京
    zoom: 15,
    
  });
}

//検索後のマップ作成
let geocoder
let aft
function codeAddress(){
  let inputAddress = document.getElementById('address').value;
  geocoder.geocode( { 'address': inputAddress}, function(results, status) {
    if (status == 'OK') {
        //マーカーが複数できないようにする
        if (aft == true){
            marker.setMap(null);
        }

        //新しくマーカーを作成する
        map.setCenter(results[0].geometry.location);
            marker = new google.maps.Marker({
            map: map,
            position: results[0].geometry.location,
            draggable: true	// ドラッグ可能にする
        });

        //二度目以降か判断
        aft = true

        //検索した時に緯度経度を入力する
        document.getElementById('lat').value = results[0].geometry.location.lat();
        document.getElementById('lng').value = results[0].geometry.location.lng();

        // マーカーのドロップ（ドラッグ終了）時のイベント
        google.maps.event.addListener( marker, 'dragend', function(ev){
            // イベントの引数evの、プロパティ.latLngが緯度経度
            document.getElementById('lat').value = ev.latLng.lat();
            document.getElementById('lng').value = ev.latLng.lng();
        });
    } else {
      alert('該当する結果がありませんでした：' + status);
    }
  });   
}

</script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCvY9IGv985UPr5MjgyML5wfuLT_82Nx94&callback=initMap" async defer></script>
<% end %>

app/views/posts/select.html.erb
<%= link_to "北海道地方へ",  posts_hokkaido_path %>

<%= link_to "東北地方へ", posts_touhoku_path %>

<%= link_to "関東地方へ", posts_kanto_path %>

<%= link_to "中部地方へ", posts_tyubu_path %>

<%= link_to "近畿地方へ", posts_kinki_path %>

<%= link_to "中国・四国地方へ", posts_path %>

<%= link_to "九州地方へ", posts_kyusyu_path %>

app/views/posts/show.html.erb
<h1>ぼらんてら</h1>
<h3>Post詳細</h3>
<div class="post">
  <p><%= @post.genre %></p>
  <p><%= @post.area %></p>
  <p><%= @post.created_at %></p>
  <%= image_tag @post.image_url, size: "250x200" if @post.image? %>
    <% if user_signed_in? %>
      <% if current_user.already_liked?(@post) %>
        <%= link_to post_like_path(@post), method: :delete do %>
          <p>いいねを取り消す</p><%= @post.likes.count %>
        <% end %>
      <% else %>
        <%= link_to post_likes_path(@post), method: :post do %>
          <p>いいね</p><%= @post.likes.count %>
        <% end %>
      <% end %>
    <% else %>
      <p>いいねの数 = </p><%= @post.likes.count %>
    <% end %>
  <%= link_to "編集する", edit_post_path(@post.id) %>
</div>

<%= link_to "投稿一覧に戻る", posts_path %>



<h2>いいねしたユーザー</h2>
  <% @post.liked_users.each do |user| %>
  <li><%= user.email %></li>
<% end %>

<% @post.tags.each do |tag| %>
  <span><%= tag.name %></span>

<% end %>


<h2>Google Map</h2>
<div id='show-map'></div>
<style>
#show-map {
  height: 400px;
  width: 100%;
}
</style>
<!-- JavaScript部分 -->
<script>
  function initShowMap() {
    let showMap = new google.maps.Map(document.getElementById('show-map'), {
      zoom: 12,
      center: { lat: <%= @post.lat %>, lng: <%= @post.lng %> },
      styles: [
        {
          stylers: [
            { "saturation": 0 },
            { "lightness": 0 }
          ]
        }
      ]
    });
    // マーカーを表示
    let marker = new google.maps.Marker({
      position: { lat: <%= @post.lat %>, lng: <%= @post.lng %> },
      map: showMap,
      title: '<%= @post.name %>'
    });
    // マーカーをクリックしたとき、詳細情報を表示
    let infowindow = new google.maps.InfoWindow({
      content: "<a href='<%= post_url(@post.id) %>'><%= @post.name %></a>"
    });
    marker.addListener('click', function() {
      infowindow.open(showMap, marker);
    });
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBkxCV4XGBt1l8ID4gCPcOBXv-Ny71LwLE&callback=initShowMap" async defer></script>
<%= link_to "お土産一覧に戻る", posts_path %>
<%= link_to "編集する", edit_post_path(@post
.id) %>

app/views/posts/touhoku.html.erb
<%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
  <%= text_field_tag :tag %>
  <%= submit_tag 'タグを追加' %>
<% end %>

<% @touhoku.each do |t| %>
  <div class="Post">
    <%= t.user.email %> 
    <%= t.name %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <p>いいねを取り消す</p><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
              <p>いいね</p><%= t.likes.count %>
            <% end %>
          <% end %>
      <% else %>
        <p>いいねの数 = </p><%= t.likes.count %>
    <% end %>

    <%= image_tag t.image_url, size: "250x200" if t.image? %>

    <%= t.created_at %>
    <%= link_to "詳細へ", post_path(t.id) %>
    <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_post_path(t.id) %>
      <%= link_to "削除する", post_path(t.id), method: :delete %>
    <% end %> 
    
  </div>
<% end %>
</div>

app/views/posts/tyubu.html.erb
<%= form_tag({controller:"posts",action:"index"}, method: :get) do %>
  <%= text_field_tag :tag %>
  <%= submit_tag 'タグを追加' %>
<% end %>

<% @tyubu.each do |t| %>
  <div class="Post">
    <%= t.user.email %> 
    <%= t.name %>
        <% if user_signed_in? %>
          <% if current_user.already_liked?(t) %>
            <%= link_to post_like_path(id: t.id, post_id: t.id), method: :delete do %>
              <p>いいねを取り消す</p><%= t.likes.count %>
            <% end %>
          <% else %>
            <%= link_to post_likes_path(id: t.id, post_id: t.id), method: :post do %>
              <p>いいね</p><%= t.likes.count %>
            <% end %>
          <% end %>
      <% else %>
        <p>いいねの数 = </p><%= t.likes.count %>
    <% end %>

    <%= image_tag t.image_url, size: "250x200" if t.image? %>

    <%= t.created_at %>
    <%= link_to "詳細へ", post_path(t.id) %>
    <% if user_signed_in? && current_user.id == t.user_id %>
      <%= link_to "編集する", edit_post_path(t.id) %>
      <%= link_to "削除する", post_path(t.id), method: :delete %>
    <% end %> 
    
  </div>
<% end %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation" data-turbo-cache="false">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= button_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), data: { turbo: false } %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<p>名前 : <%= @user.name %></p>
<p>メールアドレス : <%= @user.email %></p>
<p>プロフィール : <%= @user.profile %></p>

<% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
<% end %>

<h2>ユーザーの投稿一覧</h2>
<% @user.posts.each do |t| %>
  <%= t.user.name %>
  <%= t.name %>
  <%= image_tag t.image_url, size: "250x200" if t.image? %>
<% end %>

<h2>ユーザーがいいねした投稿一覧</h2>
<% @user.liked_posts.each do |t| %>
    <%= t.name %>
    <%= image_tag t.image_url, size: "250x200" if t.image? %>
<% end %>

<%= link_to "投稿一覧に戻る", posts_path %>